#!/bin/sh
trap '/bin/rm -f ${inFile} > /dev/null 2>&1' 0 1 2 

######################################################################
#
# Copyright 2008, 2009, 2010  Oki Data Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
######################################################################

PATH=/bin:/usr/sbin:/usr/bin
export PATH

CAT="/bin/cat"
CUT="/usr/bin/cut"
ECHO="/bin/echo"
GREP="/bin/grep"
SED="/bin/sed"

GROUP="/etc/group"

tmp_name="okijobaccounting"
inFile="/tmp/${tmp_name}.$$"

_jobid="${1}"
_user="${2}"
_title="${3}"
_options="${5}"

tmp_id=`${GREP} "^${_user}:" ${GROUP}| ${CUT} -d":" -f3 2> /dev/null`
_id=`${ECHO} ${tmp_id:-999999988} | ${SED} -e "s/.*\([0-9]\{9\}\)/\1/"`

OKIJOB_ACCT="@PJL OKIJOBACCOUNTJOB JOBACCOUNTID=${_id} USERID=\"${_user}\" JOBNAME=\"${_title}\""

${CAT} - > ${inFile}

${CAT} ${inFile} | ${SED} "/@PJL ENTER/ i\
${OKIJOB_ACCT}
"
/bin/rm -f ${inFile} > /dev/null 2>&1

exit 0
